export const chatHistory = [
    {
      id: 1,
      type: "user",
      message: "give my yesterday mails",
      timestamp: "2 min ago",
    },
    {
      id: 2,
      type: "assistant",
      message: "I'll search for your emails from yesterday to show you what you received.",
      timestamp: "2 min ago",
    },
    {
      id: 3,
      type: "assistant",
      message: "Found 11 threads after:2025/06/01 before:2025/06/03",
      timestamp: "2 min ago",
    },
    {
      id: 4,
      type: "assistant",
      message:
        "I found 11 emails from yesterday (June 2nd, 2025). Here's a summary of your emails:\n\nPromotional/Marketing emails (6):\n• CSS if(), Seamless SVG Te... CodePen newsletter about CSS if() functions, SVG text animations, and web development tutorials\n• NEW - Take Your Amazon Bu... Helium 10 promoting TikTok Shop integration for Amazon sellers\n• Win 2 Tickets to Anubh... AllEvents contest to win tickets to Anubhav Bassi comedy show in Ahmedabad\n• Good news alert! Canva highlighting their teacher support initiative and donation program\n• Welcome to Lightblock! Welcome email from Lightblock",
      timestamp: "1 min ago",
    },
  ]

  // Mock emails data
export const emails = [
    {
      id: 1,
      sender: "Google Cloud Platform, Firebase, and APIs",
      senderEmail: "CloudPlatform-noreply@google.com",
      subject: "Action required: your billing account 01D713-1C431D-7BF2CB has been suspended.",
      preview: "Google Cloud Platform account suspended due to unpaid past due amounts or errors.",
      time: "Apr 1, 5:17 AM",
      isStarred: true,
      isRead: false,
      category: "Updates",
      avatar: "G",
      avatarColor: "bg-red-500",
      content: `Dear Google customer,

You are receiving this email because you are a Google Cloud Platform, Firebase, or API customer.

Your billing account 01D713-1C431D-7BF2CB has been suspended for failure to pay past due amounts or invalid payment information. During suspension, you may experience an impact to your billing account and related Project(s) or services.

To resolve this issue, please update your payment method or pay any outstanding balance in the Google Cloud Console.`,
    },
    {
      id: 2,
      sender: "Google Cloud Support",
      senderEmail: "support@googlecloud.com",
      subject: "[Case Action Advised] Your Google Cloud Support case #58560564: General inquiry",
      preview: "Hello, Your Case #58560564 has been updated with a new message from our support team...",
      time: "Apr 3",
      isStarred: true,
      isRead: true,
      category: "Updates",
      avatar: "G",
      avatarColor: "bg-blue-500",
      content:
        "Hello, We have received your support case and our team is working on it. We will get back to you within 24 hours with an update.",
    },
    {
      id: 3,
      sender: "Google Cloud Support",
      senderEmail: "support@googlecloud.com",
      subject: "Google Cloud Support #58560564: General inquiry - Case Closed",
      preview: "Hello, We have resolved your Google Cloud Support case and it has been closed...",
      time: "Apr 3",
      isStarred: true,
      isRead: true,
      category: "Updates",
      avatar: "G",
      avatarColor: "bg-blue-500",
      content:
        "Hello, We have successfully resolved your support case. If you have any further questions, please don't hesitate to contact us.",
    },
    {
      id: 4,
      sender: "Codeforces",
      senderEmail: "codeforces@codeforces.com",
      subject: "Educational Codeforces Round 179 (Rated for Div. 2)",
      preview: "Hello, pateltejas.200...",
      time: "1:51 AM",
      isStarred: false,
      isRead: true,
      category: "Updates",
      avatar: "C",
      avatarColor: "bg-orange-500",
      content:
        "Hello, Educational Codeforces Round 179 (Rated for Div. 2) will start on June 3, 2025 at 17:35 (UTC). The round will be rated for participants with rating lower than 2100.",
    },
    {
      id: 5,
      sender: "CodePen",
      senderEmail: "hello@codepen.io",
      subject: "CSS if(), Seamless SVG Text, and a Custom Scrollbar",
      preview: "View this issue on...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Promotions",
      avatar: "C",
      avatarColor: "bg-black",
      content:
        "View this issue on CodePen. This week we're featuring CSS if() functions, seamless SVG text animations, and custom scrollbar designs.",
    },
    {
      id: 6,
      sender: "Helium 10",
      senderEmail: "support@helium10.com",
      subject: "NEW - Take Your Amazon Business to TikTok Shop",
      preview: "Hi Tejas, With love...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Promotions",
      avatar: "H",
      avatarColor: "bg-blue-600",
      content:
        "Hi Tejas, With love from the Helium 10 team! We're excited to announce our new TikTok Shop integration for Amazon sellers.",
    },
    {
      id: 7,
      sender: "nse_alerts",
      senderEmail: "alerts@nse.com",
      subject: "Funds/Securities Balance",
      preview: "Dear Investor, With reference to...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Updates",
      avatar: "N",
      avatarColor: "bg-purple-500",
      content:
        "Dear Investor, With reference to your trading account, please find your current funds and securities balance statement.",
    },
    {
      id: 8,
      sender: "AllEvents",
      senderEmail: "noreply@allevents.in",
      subject: "Win 2 Tickets to Anubhav Bassi Live Comedy Show",
      preview: "Enter to Win Free Tickets...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Promotions",
      avatar: "A",
      avatarColor: "bg-green-500",
      content: "Enter to Win Free Tickets to Anubhav Bassi Live Comedy Show in Ahmedabad. Limited time offer!",
    },
    {
      id: 9,
      sender: "Google",
      senderEmail: "security@google.com",
      subject: "Security alert for tejas.patel408@gmail.com",
      preview: "This is a copy of a security alert...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Updates",
      avatar: "G",
      avatarColor: "bg-red-500",
      content:
        "This is a copy of a security alert we sent to your recovery email. We detected a new sign-in to your Google Account.",
    },
    {
      id: 10,
      sender: "Canva",
      senderEmail: "hello@canva.com",
      subject: "Good news alert!",
      preview: "Five teachers get the surprise of a lifetime...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Promotions",
      avatar: "C",
      avatarColor: "bg-purple-600",
      content:
        "Five teachers get the surprise of a lifetime with our new education initiative. Learn more about our teacher support program.",
    },
    {
      id: 11,
      sender: "Notion Team",
      senderEmail: "team@notion.so",
      subject: "A new device logged into your account",
      preview: "Review a recent login from a new device...",
      time: "Yesterday",
      isStarred: false,
      isRead: true,
      category: "Updates",
      avatar: "N",
      avatarColor: "bg-black",
      content: "Review a recent login from a new device. If this wasn't you, please secure your account immediately.",
    },
  ]